POWERS = [
    'Fatigue Resistance',
    'Acute Senses',
    'Attribute Increased',
    'Unnatural Size',
    'Inhumanity/Zen',
    'Aquatic Breathing',
    'Reduced Physical Needs',
    'Natural Immunity to an Element',
    'Psychological Immunity',
    'Natural Weapons',
    'Additional Attacks',
    'Increased Damage',
    'Increased Reaction',
    'Damage Energy',
    'Armor Modifier',
    'Special Attack',
    'Poisoned Attack',
    'Added Mystical Effect',
    'Increased Critical',
    'Special Trapping',
    'Supernatural Attack',
    'Elemental Attack',
    'Special Movement',
    'Automatic Transport',
    'Increased Movement',
    'Natural Flight',
    'Mystical Flight',
    'Increased Physical Resistance',
    'Mystical/Psychic Resistance',
    'Regeneration',
    'Physical Immunity',
    'Magical Immunity',
    'Matrix Immunity',
    'Damage Barrier',
    'Physical Armor',
    'Mystical Armor',
    'Innate Magic',
    'Innate Psychic Abilities',
    'Metamorphosis',
    'Invisibility / Undetectable',
    'Aura',
    'Special Means of Vision',
    'Supernatural Detection'
]