[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anima"
version = "0.0.0"
authors = [
  { name="Dez", email="desmeraldoo@gmail.com" },
]
description = "Utils for assisting players and GMs in the tabletop roleplaying game Anima: Beyond Fantasy"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/desmeraldoo/anima"
"Bug Tracker" = "https://github.com/desmeraldoo/anima/issues"

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true
no_namespace_packages = true
